### ISSUE TITLE
Can't get 2.4 to run with spree_variant_options

### ISSUE THREAD

**Issue by garethbradley** [AgilTec/spree_variant_options#5]
Hi,

I've had a go at putting this into my gemfile which looks like this

``` ruby
gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_gateway', :git => 'https://github.com/spree/spree_gateway.git', :branch => '2-4-stable'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-4-stable'
# gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '2-4-stable'
gem 'spree_variant_options', :github => 'AgilTec/spree_variant_options', :branch => '2-4-stable'
```

which bundles fine. However, when running the server in dev with "rails s", I get the following error:

controllers/spree/products_controller_decorator.rb:1:in `<top (required)>': private method`include' called for Spree::ProductsController:Class (NoMethodError)

I've deleted the Gemfile.lock and updated all gems including --system, but I'm afraid I'm not getting anywhere. My site has been updated from an older version of Spree (2.1 rings a bell).

Many thanks - this gem is exactly what I've been looking for!!!

Regards,
Gareth

**Comment by mvidaurre** [comment]
Are you using `bundle exec rails s`?

**Comment by EduardoMarchese** [comment]
Hi,
I get the same error as his
<pre>
.rvm/gems/ruby-2.0.0-p576/bundler/gems/spree_variant_options-670c5b117e8d/app/controllers/spree/products_controller_decorator.rb:1:in `<top (required)>': private method `include' called for Spree::ProductsController:Class (NoMethodError)
</pre>
Bundle goes fine, but when I try to:
rails g ispree_variant_options:install
I get the error above.
GemFile is as follow:
<pre>
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


gem 'spree', '2.4.2'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_variant_options', :github => 'AgilTec/spree_variant_options', :branch => '2-4-stable'
#gem 'spree_fancy', :github => 'spree/spree_fancy', :branch => '2-4-stable'
#gem 'spree_cloudzoom', :github => 'mvidaurre/spree_cloudzoom', :branch => '2-4-stable'
</pre>
I am not using <pre>bundle exec rails s</pre>
Thanks in advance for your answer
E.M.

**Comment by tobiaszwaszak** [comment]
Hello,

i have the same problem

i try run test & demo and these are works correctly

**Comment by EduardoMarchese** [comment]
Hi Tobia,
so is spree_variant_options working fine for you? I still have the same issue

**Comment by tobiaszwaszak** [comment]
no, only demo
when i try use it in my spree code i have same error as you

**Comment by EduardoMarchese** [comment]
Mine doesn't word in demo either

**Comment by mvidaurre** [comment]
Could you please créate a gist with you Gemfile.lock? in order to check the dependencias that you have in you application

**Comment by tobiaszwaszak** [comment]
https://gist.github.com/tobiaszwaszak/1aeb84ed796db680a35f

**Comment by EduardoMarchese** [comment]
Hi mvidaurre, thanks for your answer
https://gist.github.com/fb00cc8bc48c353d3a65.git

**Comment by tobiaszwaszak** [comment]
The solution is:
Change ruby version to 2.2.0

**Comment by tobiaszwaszak** [comment]
but it is not a finish of my problems
when i try add something to cart (with variants) i have that error

```
NoMethodError in Spree::OrdersController#populate

undefined method `+' for nil:NilClass

app/controllers/spree/orders_controller.rb:49:in `populate'

```
https://www.dropbox.com/s/xwu12liyq1abp4t/Zrzut%20ekranu%202015-02-11%2021.52.05.png?dl=0

**Comment by EduardoMarchese** [comment]
tobiaszwaszak that didn't fix my issue, I do have the same issue as before

**Comment by vijayp146** [comment]
Hello 
I am getting this error... uninitialized constant Spree::OptionValue::Spree::OptionValueVariant

gem 'spree', '3.0.8'
gem 'spree_variant_options', :git => 'git://github.com/AgilTec/spree_variant_options.git', :branch => "3.0.0"
